import Footer from "./components/Footer";
import Header from "./components/Header";
import { CartProvider } from "../context/CartContext";
import "./globals.css";


export const metadata = {
  title: "Grocery App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
      <Header></Header>
      {children}
      <Footer/>
      </CartProvider>
      <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
      </body>
    </html>
  );
}
